name: task_calendar
description: A new Flutter project.

publish_to: 'none' 
#* Flutter v3.10.6

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  intl: any
  flash: ^3.0.5+1
  flutter_svg: ^2.0.7
  in_date_utils: ^1.1.0
  table_calendar: ^3.0.9
  shared_preferences: ^2.2.0
  connectivity_plus: ^4.0.2

  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  shimmer: ^3.0.0
  dartz: ^0.10.1
  get_it: ^7.6.0
  logger: ^2.0.1
  dio: ^5.3.0

  freezed: ^2.4.1
  freezed_result: ^1.0.3+1
  freezed_annotation: ^2.4.1
  freezed_collection: ^0.0.3

  json_serializable: ^6.7.1
  json_annotation: ^4.8.0

  auto_route: ^7.7.1
  auto_route_generator: ^7.2.0

  injectable: ^2.1.2
  injectable_generator: ^2.1.3
  pull_to_refresh: ^2.0.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0
  build_runner: ^2.4.6

flutter:

  uses-material-design: true

  fonts:
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter-Regular.ttf
        weight: 400
      - asset: assets/fonts/Inter-Medium.ttf
        weight: 500
      - asset: assets/fonts/Inter-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Inter-Bold.ttf
        weight: 700
      - asset: assets/fonts/Inter-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Inter-Black.ttf
        weight: 900
